name: FactionsProEdited
author: MikeyHampton
version: 1.0.0
main: FactionsPro\FactionMain
api: [3.0.0, 3.3.2, 4.0.0]
softdepend:
    - PureChat
    - AntiSpamPro
commands:
    f:
    description: List Faction Commands
    permission: f.command
permissions:
    f.command:
    default: true
